### ISSUE TITLE
The purpose of bootrom.rk3328.bin and bootrom_rk3399.bin

### ISSUE THREAD

**Issue by dmikushin** [Marcin666/RK3328_Uboot_SPI#1]
Hi @MarcinWad,

Congratulations on booting RK3328 from SPI, excellent work, thank you for a lot of effort.

It's interesting to know what is the purpose of two files - `bootrom.rk3328.bin` and `bootrom_rk3399.bin`. They don't seem to be used by any build step in your instruction.

**Comment by MarcinWad** [comment]
Hello,
Those are dumped internal SOC bootrom which i disassembled and found out that bootrom talks to SPI only 3-byte commands.
I left it just for further investigation if someone wants to play with it.

**Comment by dmikushin** [comment]
Oh I see, thank you
