### ISSUE TITLE
Boot the kernel also from the SPI chip as well?

### ISSUE THREAD

**Issue by dmikushin** [Marcin666/RK3328_Uboot_SPI#2]
Hi @MarcinWad,

How do you envision the next step of kernel boot? What would be the easiest way to boot the kernel also from the SPI chip?

**Comment by MarcinWad** [comment]
Okay,

**Comment by MarcinWad** [comment]
Done

**Comment by dmikushin** [comment]
Sorry, I'm not sure what do you mean. I was wondering how to place the kernel also on the SPI chip. I guess we need to have some u-boot environment for that?

**Comment by MarcinWad** [comment]
Check updated README.md

**Comment by dmikushin** [comment]
Oh I see, amazing, thanks a lot :+1:

**Comment by dmikushin** [comment]
Oh, one thing: in the end you have:

```
setenv bootargs earlycon=uart8250,mmio32,0xff130000 console=ttyFIQ0 mtdparts=spi0.0:0x200000(U-Boot),0x500000(Kernel),0x500000(Rootfs),0x100000(Data),-(Unused)  rootfstype=squashfs root=/dev/mtdblock2
setenv bootcmd "sf probe; sf read 0x400000 0x200000 0x500000; bootm 0x400000"
saveenv
```

Environment is supposed to be stored in SPI as well, right? Would these commands work, given that we need to flash them to SPI?

**Comment by MarcinWad** [comment]
As long as you already Flashed idb_loader.img to SPI and booted from SPI - you already work on SPI.

Yep, In Uboot config file you have:

 CONFIG_ENV_IS_IN_SPI_FLASH=y
 CONFIG_ENV_SIZE=0x2000
 CONFIG_ENV_OFFSET=0x140000
 CONFIG_ENV_SECT_SIZE=0x2000

**Comment by dmikushin** [comment]
Right, but would U-boot be able to flash new environment to SPI, by simply running `saveenv`?

**Comment by MarcinWad** [comment]
Yes. It stores env at at the end of flash idb_loader.img space (0x140000).

Check by sf probe and sf read/write if they work.
