### ISSUE TITLE
Some disagreement between TPL and SPL

### ISSUE THREAD

**Issue by dmikushin** [Marcin666/RK3328_Uboot_SPI#4]
Hi @MarcinWad ,

I've noticed some disagreement between TPL and SPL in the guide, which feels like a typo. This line creates `tpl/u-boot-tpl.bin`:

```
 ./tools/mkimage -n rk3328 -T rksd -d tpl/u-boot-tpl.bin idbloader.img
 ```

But later `spl/u-boot-spl.bin` is used, which does not exist:

```
 cat spl/u-boot-spl.bin >> newidb.img
 ```

I think both of them should exist, but only tpl is created. Is a command to create spl missing? And is a command to write  tpl missing as well?

**Comment by MarcinWad** [comment]
File spl/u-boot-spl.bin should exist after Uboot compilation. Maybe you disabled SPL in configuration?

**Comment by dmikushin** [comment]
Hi @MarcinWad thank you, yes this is my mistake: I appended CONFIG_ settings to the end of file, however only the first occurrences are accounted, where SPL is disabled indeed.
