### ISSUE TITLE
RK3328 BROM TPL load address clarification

### ISSUE THREAD

**Issue by dsx724** [Marcin666/RK3328_Uboot_SPI#8]
RK3399 BROM loads TPL from byte address 0x0 with 2K per 4K block for TPL and SPL.
https://elixir.bootlin.com/u-boot/v2019.07-rc4/source/doc/README.rockchip
```
rkspi.c produces an image consisting of a header and u-boot-spl-dtb.bin. The
resulting image is then spread out so that only the first 2KB of each 4KB
sector is used. The header is the same as with rksd and the maximum size is
also 32KB (before spreading). The image should be written to the start of
SPI flash.
```
However you have the TPL going to byte address 0x8000 instead of the start of SPI flash.

I'm a little confused which is right since rockchip-u-boot.dtsi SPI section make no mention of an offset and works directly flashed to 0. Can you provide some clarification?

**Comment by dsx724** [comment]
Figured it out thanks.

**Comment by MarcinWad** [comment]
Sorry for late reply. According to what you wrote - my tutorial is for RK3328 not RK3399 so propably this is the problem

**Comment by dsx724** [comment]
RK3328 does not have the 2K/4K SPI bug that RK3399 does. I didn't see the rksd instead of rkspi in your code initially. The upstream documentation is incorrect as it was expecting the bug on all RK33XX. I have already raised the issue and it should be corrected eventually.

**Comment by MarcinWad** [comment]
Thats what i thought. RK3399 has this SPI bug but i didnt have to bother with it as i had different problem at all (3-byte addressing). 

Glad you figured this out.
